
# This allows token to :
# - Be used to configure and manage database engine 
# - Extract WordPress users credentials generated by vault

path "database/creds/wp-db-role" {
  capabilities = ["read"]
}

path  "kv/wp-admin-creds" {
  capabilities = ["read"]
}

path  "kv/wp-author-creds" {
  capabilities = ["read"]
}
